//user
export const FETCH_USER = {
    FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
}

export const USER_LOGIN = {
    STATE_TRUE: 'TRUE',
    STATE_FALSE:'FALSE',
}